/**
 * Hand-drawn banners for side events whose partner published no artwork of their own.
 *
 * SHARED ON PURPOSE. This lived inside lib/sideEvents.ts, serving Program 2026 only. When
 * /partner-events gained event artwork it showed nothing for these three, because the override
 * was not reachable from there — the same near-copy trap that made the two pages print different
 * venue lines. One module, imported by both (Auri, 2026-08-10).
 *
 * The files are built by hand and live in `public/side-events/`, generated by
 * `C:\Users\User\Desktop\Side Events\make_banner.py` — see the progress.md beside it for the
 * layout, the Gemini prompt recipe and the open items on each banner.
 *
 * AN ENTRY HERE WINS over the partner's own scraped og:image — see the `??` order at both call
 * sites, which agree since 2026-08-19. Listing a title is a deliberate choice to show TechBBQ's
 * banner, so a ticketing page that publishes artwork later does not silently replace it. The flip
 * side: a banner carries whatever the date and venue were on the day it was drawn, so when the
 * partner's own artwork should take over, DELETE the line rather than leaving both in place.
 */
import { baseUrl } from "@/lib/photo";

/**
 * Titles do not match exactly across the two systems, so compare them loosely: lowercase,
 * punctuation and accents out. That is what pairs Brella's "The Next Generation of Finance: CFO
 * Round Table Dinner" with Airtable's "CFO Round Table Dinner".
 */
export function titleKey(s: string): string {
  return (s || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9 ]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

// KEYED ON titleKey(), not on the raw title, because these names are inconsistent across the two
// sources ("BSR Go-abroad Co-ceation Seminar" is spelt that way in Airtable, typo included). An
// exact-match key would silently match nothing and show no banner, which is indistinguishable
// from not having added one.
//
// NOT IN HERE, deliberately: BSR Go-abroad. It looked like a fourth missing image and was
// actually a MANGLED URL — Eventbrite writes its og:image with `&amp;` and the scraper was not
// decoding entities, so the proxy answered 400 and the card hid its own figure. Fixed properly in
// lib/eventPages.ts, so BSR shows Eventbrite's real artwork. The hand-drawn BSR banner exists in
// the Desktop folder and is NOT used, and should not be: its date and venue were guesses, and a
// wrong venue on techbbq.dk is worse than no picture.
const ARTWORK_OVERRIDES: Record<string, string> = {
  "cto connect": "cto-connect.webp",
  "techbbq biotech university spinouts discussion 2026": "biotech-spinouts.webp",
  "the nordic paradox from mapping to action": "nordic-paradox.webp",
  "techbbq run warm up with danske bank growth cykom": "techbbq-run.webp",
  "unlocking nordic private markets": "nordic-private-markets.webp",
};

/** The banner for a title, or null when there is no hand-drawn one. Pass a titleKey(). */
export function artworkOverride(key: string): string | null {
  const file = ARTWORK_OVERRIDES[key];
  if (!file) return null;
  // ABSOLUTE, via the same baseUrl() every other feed uses. A bare "/side-events/..." works on
  // the dashboard and silently 404s inside the embed, where the browser resolves it against
  // techbbq.dk. That exact mistake shipped once on the partner wall and produced 104 empty tiles.
  return `${baseUrl()}/side-events/${file}`;
}
